- hosts: localhost
  gather_facts: false
  tasks:
  - debug: msg={{'https://sps-build-deploy.s3.amazonaws.com/ansible/ansible-pb-loc-api-0.0.7.tgz' | regex_replace('https://(.*).s3.amazonaws.com/', 's3://\\1/' ) }}
